/*Insert Author record*/
INSERT INTO AUTHOR (AUTHORID, NAME) VALUES (1,'Alex Lake');
INSERT INTO AUTHOR (AUTHORID, NAME) VALUES (2,'Sherlock Holmes');

/*Insert book records*/
INSERT INTO BOOK (BOOKID,TITLE,AUTHORID) VALUES (10000001,'A Study in Scarlet',2);
INSERT INTO BOOK (BOOKID,TITLE,AUTHORID) VALUES (10000002,'The Valley of Fear',2);
