DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS AUTHOR;


CREATE TABLE AUTHOR
(
    AUTHORID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100)

);
CREATE TABLE BOOK
(
    BOOKID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE  VARCHAR(100),
    AUTHORID    INT,
    constraint FK_Author_Id foreign key (AUTHORID) references AUTHOR (AUTHORID)
);
